//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusChronicles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> ID_rolRol { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
